FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

COPY .eslintrc.json ./

COPY .prettierrc ./

RUN npm install

COPY . .

# Build for production.
# RUN npm run build

# COPY . .

EXPOSE 8083

CMD [ "npm", "start" ]
# FROM node:18-alpine